import cv2

#to import a pre-built file containing weights for extracting facial features from an image
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

#to capture live video through webcam
cap = cv2.VideoCapture(0)
while True:
    _, image = cap.read()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,1.1,4)

    #generating a rectangular boundary using coordinates generated by face cascade
    for(x,y,w,h) in faces:
        cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 2)

    cv2.imshow('image',image)
    k=cv2.waitKey(30) & 0xff
    if k==27:
     break

# to close the image window
cap.release()
